[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "primes"
version = "0.1.0"
description = "A library for primality testing"

[tool.setuptools]
packages = ["src"]